### ISSUE TITLE
[UI | BUG] Tray icon menu has invisible text

### ISSUE THREAD

**Issue by Atrate** [bkueng/qMasterPassword#10]
As in the attached screenshot, both qMasterPassword and Riot are using AppIndicators to show their tray icons, but qMasterPassword's menu has invisible (or no) text.

Does not happen my other device, when not using AppIndicators.

![menu](https://user-images.githubusercontent.com/26827848/75522472-f9c31400-5a01-11ea-819d-a08cf597d996.png)

System info:
Arch Linux
GNOME Shell 3.34.4 w/ libappindicator support plugin
qMasterPassword v1.2.2

**Comment by bkueng** [comment]
Indeed, there seems to be a bug in Qt. I fixed it in https://github.com/bkueng/qMasterPassword/commit/d4b679f65790a012489de8884f55606f538d2cdf.
