### ISSUE TITLE
New site not saved when quitting before logging out

### ISSUE THREAD

**Issue by teutat3s** [bkueng/qMasterPassword#15]
Hello,
thank you very much for this great implementation of the mpw algorithm!

I noticed when using `qMasterPassword` on Linux with the Wayland compositor `sway`, that when quitting the application before pressing the "Logout" button, sites I added before get lost and are not visible anymore when I re-open qMasterPassword and re-login.

Can someone reproduce this? I'd be glad if I can be of help to debug this and thereby hopefully fix and improve the application.

**Comment by bkueng** [comment]
Hi!
Saving settings should be independent from the login state, so I think the signal isn't triggered on exit:
https://github.com/bkueng/qMasterPassword/blob/master/src/main_window.cpp#L523

You can test adding another `saveSettings()` call right after adding/editing/deleting a site, e.g.:
https://github.com/bkueng/qMasterPassword/blob/master/src/main_window.cpp#L606

**Comment by teutat3s** [comment]
Thank you @bkueng, that works nicely here. Would you like me to submit a PR?
I am maybe quitting qMasterPassword in an unexpected way (on NixOS Linux, with `sway` on Wayland using [this `kill` hotkey combintaion](https://github.com/swaywm/sway/blob/cd1ee0e172a10a3f8a420ff20aa1a69d46c7b4ad/config.in#L69). Do you think saving directly after adding / editing would be the right fix to this?

Often, I don't even kill it deliberately, because I leave it running in the background ([sway's so-called `scratchpad`](https://github.com/swaywm/sway/blob/cd1ee0e172a10a3f8a420ff20aa1a69d46c7b4ad/config.in#L162-L173)) and it just gets killed by the OS when rebooting / shutting down. It would be really nice to not lose any changes then, either.

**Comment by bkueng** [comment]
Thanks, for testing, yes I'd appreciate a PR. I'd rather save once too many times than losing data.
