### ISSUE TITLE
New Icon?

### ISSUE THREAD

**Issue by bgiesing** [bkueng/qMasterPassword#2]
On my display, the current icon looks kinda blurry. Also it has a couple of other problems:
- Outdated design
- Icon doesn't match the official apps making harder to recognize.

Here is a proposed icon I made using the [Material Design Icon Generator](http://jgilfelt.github.io/AndroidAssetStudio/icons-launcher.html):
![logo](https://cloud.githubusercontent.com/assets/7895463/6316097/98ecd864-b9de-11e4-9045-9495b03699ec.png)

@bkueng, I think this new icon would solve all of these issues.

**Comment by bkueng** [comment]
cool! You are right I wasn't completely happy with the current icon either. Although design is always a bit subjective.
Do you happen to have it as svg?

**Comment by bgiesing** [comment]
Sorry I don't, the generator only provides pngs.

**Comment by bkueng** [comment]
ok, I will use this one then.
