### ISSUE TITLE
[release] tag a new release with recent fixes

### ISSUE THREAD

**Issue by teutat3s** [bkueng/qMasterPassword#20]
I'd like to package all the recent commits since https://github.com/bkueng/qMasterPassword/compare/v1.2.2...master for NixOS,
and having a new release for that would be great.

https://github.com/NixOS/nixpkgs/pull/157282

Could you please tag a new release? I don't care so much about the windows binaries, so a simple `git tag` would suffice.

**Comment by bkueng** [comment]
Done

**Comment by teutat3s** [comment]
Thank you!
