### ISSUE TITLE
Saving a site doesn't actually save site state

### ISSUE THREAD

**Issue by zetaomegagon** [bkueng/qMasterPassword#24]
I added several sites to qMasterpassword; then had the unfortunate incident where my machine rebooted on its own. When re-logging into qMasterpassword the sites weren't there.

I added a bunch of dummy sites to test. I made sure I saved them. Then I rebooted my machine without logging out of qMasterpassword. Same thing happened.

I tested again, but logged out of qMasterpassword first. This saved the site data.

Is it true that qMasterpassword only saves site state on logout?

If so, can this be changed to save site state when hitting "save"?

Thanks!

**Comment by zetaomegagon** [comment]
Sorry for the delay. I found [this closed issue](https://github.com/bkueng/qMasterPassword/issues/15) and [this merged pr](https://github.com/bkueng/qMasterPassword/pull/16/commits/639b4da9a4a6fdd2accae732302ce845422099e3), which pertain to my currently open issue.

Summary is that `saveSettings()` was added as the final step of creating, editing, or deleting an entry. Based on this, I wanna compile from source and see if entries still aren't saved on dirty exit from the application. My thought is that Fedora is just packaging an old version.

I'll update after testing...tho not sure when I'll get around to that. No promises.

**Comment by zetaomegagon** [comment]
Version is `1.2.2`

```
[zetaohm@panda ~]$ qMasterPassword --version
v1.2.2
```

**Comment by bkueng** [comment]
You're right, it's only in v1.2.3. I'll push an update.

**Comment by zetaomegagon** [comment]
Sorry about the almost 1.5 year plus delay. :grimacing:

It's working
