### ISSUE TITLE
Add User window is too narrow on Linux

### ISSUE THREAD

**Issue by xandark** [bkueng/qMasterPassword#25]
![Screenshot 2023-07-03 (21∶59∶56)](https://github.com/bkueng/qMasterPassword/assets/5048913/3505933a-afe9-40e3-8568-c92dc472f290)

There is not much space to type in the first password and the text label for the checkbox cannot be read, it goes past the window boundary.

**Comment by bkueng** [comment]
Could you give https://github.com/bkueng/qMasterPassword/pull/28 a try?

**Comment by xandark** [comment]
Fixed! Thanks :)
![Screenshot 2023-07-05 (20∶55∶53)](https://github.com/bkueng/qMasterPassword/assets/5048913/7c4e7859-8c7e-42f8-bf53-2314322aa5c8)

**Comment by xandark** [comment]
Plus, the spacing of the controls is better now too.
