### ISSUE TITLE
Suggest having pop-up tooltips when hovering over icons

### ISSUE THREAD

**Issue by xandark** [bkueng/qMasterPassword#26]
The icons on my screen are rather small and it's not immediately apparent what they do. 

It took a bit of experimentation to figure out what the add user, modify user, and delete user icons did. (The minus sign on the delete user is small.)

Also, the 3 icons in the table to view the password, etc, would benefit from having tooltips.

**Comment by bkueng** [comment]
Do you want to create a PR with better icons and tooltips?

**Comment by xandark** [comment]
I see you're looking for help, but sorry, I don't have the skills.

**Comment by bkueng** [comment]
Alright no problem, I'll have a look.

**Comment by bkueng** [comment]
I finally got around to do this (https://github.com/bkueng/qMasterPassword/commit/315348b2d1299658fad9f046f91d67d54970c3c0 and https://github.com/bkueng/qMasterPassword/commit/48729996d74b2b62ee2a7eecc9338a8c977cce50).

![](https://github.com/bkueng/qMasterPassword/blob/main/screenshots/main_window.png?raw=true)

**Comment by xandark** [comment]
Works and looks great, thanks!
