### ISSUE TITLE
Update README to reflect libscrypt library already included in standard Debian repos

### ISSUE THREAD

**Issue by xandark** [bkueng/qMasterPassword#27]
In the Dependencies section of the README, it mentions the libscrypt library with a link to another git repo. 

Under Debian/Ubuntu, this package is already in the standard "universe" repository and can be installed from the `libscrypt-dev` package. 

I built qMasterPassword this way and it seems to work fine.

**Comment by bkueng** [comment]
Right, the README is generic, but I can add the hint for Debian/Ubuntu

**Comment by bkueng** [comment]
Done in https://github.com/bkueng/qMasterPassword/commit/ba2813d506a615630ebcb66000c9198e88d56157
