### ISSUE TITLE
"@" does not work by using autotype funktion

### ISSUE THREAD

**Issue by chrisWith** [bkueng/qMasterPassword#3]
Hi, 
app works great in Archlinux! 
I figuard out, by using the autotype function that the "@" in the unser name is not transfered. 

I'm using SwagArch with all surretn updates. 

regards
Chris

**Comment by bkueng** [comment]
Hi Chris

The @ works fine for me. It might be an issue with the configured keyboard layout? Can you debug this yourself?

best
Beat

**Comment by chrisWith** [comment]
Hi Beat, 
Thank you very much for your answer.  
it's weared -by using the paste targed e.x. notepad everything is good. But by using Firefox no "@" symbol is pasted and in Chrome the "@" work but the browser does not response on it. 
If everything is working on your machine good, I'll try my best for debugging. 

Gread App!!! 

reg
Chris

**Comment by bkueng** [comment]
That is strange. Yes it works for me with Firefox.
