### ISSUE TITLE
FTBFS with qt6-qtbase-devel >= 6.5.0

### ISSUE THREAD

**Issue by stefanb2** [bkueng/qMasterPassword#30]
While trying to unretire the package for Fedora, I noticed that release `v1.2.4`  brought Qt6 support.

I updated the SPEC file accordingly and ran into a build failure during the `%check` phase. There is an API change in `QXmlStreamReader::name()` from [Qt5](https://doc.qt.io/qt-5.15/qxmlstreamreader.html#name) to [Qt6](https://doc.qt.io/qt-6/qxmlstreamreader.html#name) that breaks compiling the tests.

With this simple fix it compiles under Qt6. As far as I understand the API documentation this should work fine for Qt5 too:

~~~diff
diff -up qMasterPassword-1.2.4/test/test.cpp.ORIG qMasterPassword-1.2.4/test/test.cpp
--- qMasterPassword-1.2.4/test/test.cpp.ORIG    2022-11-05 14:08:49.000000000 +0200
+++ qMasterPassword-1.2.4/test/test.cpp 2023-10-03 12:13:32.151983217 +0300
@@ -48,10 +48,10 @@ void UnitTests::runTests_data() {
        DataTree test_cases;
 
        QVERIFY(xml.readNextStartElement());
-       QVERIFY(xml.name() == "tests");
+       QVERIFY(xml.name().toString() == "tests");
 
        while (xml.readNextStartElement()) {
-               if (xml.name() == "case") {
+               if (xml.name().toString() == "case") {
                        TestNode node;
                        QString id = xml.attributes().value("id").toString();
                        node.parent = xml.attributes().value("parent").toString();
~~~

**Comment by bkueng** [comment]
Thanks, I applied your fix in https://github.com/bkueng/qMasterPassword/commit/5cc45bcb7ea662780999ee97c15e2407dee9836b, and tested with Qt5.
