### ISSUE TITLE
[feature] get rid of X11 dependency

### ISSUE THREAD

**Issue by stefanb2** [bkueng/qMasterPassword#32]
AFAIU the keyboard shortcut code is responsible for the dependency on X11. With desktops moving to Wayland there should be a better solution. I'm not sure if depending on X11 makes Qt use X11 instead of Wayland on a Wayland desktop.

I see three options. Please note that I haven't researched them yet, so some of them may be impossible. In order of preference:

1. figure out how to implement keyboard shortcuts using Qt APIs. If this isn't possible with Qt5, then a Qt6-only solution would be acceptable.

2. provide a Wayland implementation and determine at runtime which one to use. This wouldn't remove the X11 build dependency, but at least `qMasterPassword` wouldn't show up as X11 client at runtime.

3. provide a way to disable shortcuts at build time, f.ex. unset a flag when the build can't find X11 headers. Not nice, but better having to depend on X11.

**Comment by bkueng** [comment]
Agreed, we should remove the X11 dependency.
I have not done in-depth research, but this might be an option: https://github.com/ReimuNotMoe/ydotool. It accesses `/dev/uinput`, but that requires root.

**Comment by teutat3s** [comment]
Just chiming in here, I use `qMasterPassword` with wayland (`sway`) and it starts as a wayland native application for me. Keyboard shortcuts work fine for me.

EDIT: I tested more keyboard shortcuts and now I see what's not working on wayland: all in-app shortcuts work fine, but those for switching to a different window and pasting stuff do not.

**Comment by teutat3s** [comment]
The sway wiki has a useful collection of programs that might be helpful for this issue as well:
https://github.com/swaywm/sway/wiki/Useful-add-ons-for-sway#keyboardinput

**Comment by stefanb2** [comment]
This issue is **not** about "shortcuts don't work with Wayland", but that the application connects to the X11 server when rendered by Wayland.

> Just chiming in here, I use `qMasterPassword` with wayland (`sway`) and it starts as a wayland native application for me. Keyboard shortcuts work fine for me.

With `xcb` it creates two X11 client connections

~~~sh
$ QT_QPA_PLATFORM=xcb qMasterPassword &
$ lsX11ClientConnections | grep qMasterPassword
      2 "qMasterPassword"
~~~

With `wayland` it still creates a X11 client connection

~~~sh
$ QT_QPA_PLATFORM=wayland qMasterPassword &
$ lsX11ClientConnections | grep qMasterPassword
      1 "qMasterPassword"
~~~

1. for `lsX11ClientConnections` see [here](https://unix.stackexchange.com/a/700637)
2. the unnecessary 2nd client connection could probably be avoided by calling `QX11Application::display()` instead of `XOpenDisplay()`
> ..., but those for switching to a different window and pasting stuff do not.

I concur and I'm not really surprised about that, because that probably uses some X11 window functionality. So it won't work with applications rendered by Wayland, f.ex. modern web browsers.

**Comment by stefanb2** [comment]
I wonder why not use [Qt native key press events](https://doc.qt.io/qt-6/qkeyevent.html#details) instead? I guess the only loss of functionality would be the "next window + ...." stuff.

**Comment by teutat3s** [comment]
That does not work on wayland anyway 😄 so no loss for me. ✌🏼

**Comment by stefanb2** [comment]
> https://github.com/ReimuNotMoe/ydotool. It accesses `/dev/uinput`, but that requires root.

If I understand this correctly, the tool comes with a background daemon `ydotoold` that probably handles the root part. The cliebt part seems to be running with user rights.
