### ISSUE TITLE
improvement: copy function only for user in shortcut

### ISSUE THREAD

**Issue by chrisWith** [bkueng/qMasterPassword#4]
Hi, it would be great if there is a copy funktion for only the user name. 

reg.

**Comment by bkueng** [comment]
That should be easy to add. Are you in a position to create a pull request?

**Comment by chrisWith** [comment]
I'm sorry - have no permission on pull request...

**Comment by bkueng** [comment]
You don't need permissions, you can create a fork: https://help.github.com/articles/fork-a-repo/

**Comment by bkueng** [comment]
I added the username copy function with shortcut 'U' in https://github.com/bkueng/qMasterPassword/commit/47721e79e8128afaf421de34005947e475274327.
