### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Atrate** [bkueng/qMasterPassword#9]
Hello,

Are you accepting translations? If so, what files need to be modified?

**Comment by bkueng** [comment]
Hi

Yes, sure. It's a Qt project, so it should be fairly straight-forward. Some preparations will be required, as documented here: https://doc.qt.io/qt-5/internationalization.html#enabling-translation. Is that something you can/want to look into?

**Comment by Atrate** [comment]
I don't really have any experience with Qt development, but I can edit XML/other localization files when needed without a problem and make a PR.

**Comment by bkueng** [comment]
Ok, I'll look into it and let you know once I have set it up.

**Comment by bkueng** [comment]
Which langage will you translate?

**Comment by Atrate** [comment]
Polish

**Comment by bkueng** [comment]
You can translate the `translation_pl.ts` file in https://github.com/bkueng/qMasterPassword/tree/translation/data/translations (branch `translation`) using [Qt Linguist](https://doc.qt.io/qt-5/linguist-translators.html). Afterwards you can send me the translated .ts file (directly or preferably via pull request).

**Comment by Atrate** [comment]
~~Sure! If the source and translated text of a string are the same, should I paste it in the "translation" fielt or just accept it without inputting anything, @bkueng ?~~

Now that I think about it, they should be copied, makes more sense.
